core/urls.py
from django.urls import path 
from . import views


app_name = 'core'

urlpatterns = [
    path('', views.index, name="index"),
    path('login', views.login, name="login"),
    path('signup', views.signup, name="signup"),
    path('logout', views.logout, name="logout"),
    path('movie/<str:pk>', views.movie, name='movie'),
    path('genre/<str:pk>', views.genre, name='genre'),


    path('my-list', views.my_list, name="my-list"),
    path('add_to_list', views.add_to_list, name="add_to_list"),
    path('search', views.search, name="search"),
]

netflix_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls'))
]



if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
import uuid 
from django.utils import timezone
from django.conf import settings
# Create your models here.


class Movies(models.Model):

    class Meta:
        verbose_name_plural = "Movie"

    GENRE_CHOICES = {
        ('action', 'Action'),
        ('comedy', 'Comedy'),
        ('drama', 'Drama'),
        ('horror', 'Horror'),
        ('romance', 'Romance'),
        ('science', 'Science Fiction'),
        ('fantasy', 'Fantasy'),
    }

    uu_id = models.UUIDField(default=uuid.uuid4)
    title = models.CharField(max_length=255)
    description = models.TextField()
    release_date = models.DateField()
    genre = models.CharField(max_length=150, choices=GENRE_CHOICES)
    length = models.PositiveIntegerField()
    image_card = models.ImageField(upload_to='movie_images/')
    image_cover = models.ImageField(upload_to='movie_images/')
    video = models.FileField(upload_to='movie_videos/')
    movie_views = models.IntegerField(default=0)
    parental_rating = models.CharField(max_length=50)
    created_date = models.DateTimeField('date created', default=timezone.now)

    def __str__(self):
        return self.title
    

class MovieList(models.Model):

    class Meta:
        verbose_name_plural = "MovieList"


    owner_user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, )
    movie = models.ForeignKey(Movies, on_delete=models.CASCADE)

    def __str__(self):
        return self.owner_user

core/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User, auth
from django.contrib import messages
from django.contrib.auth.decorators import login_required
import re
from django.http import JsonResponse
from .models import *
# Create your views here.

@login_required(login_url='core:login')
def index(request):
    # movies = Movies.objects.all().order_by('-created_date')
    movies = Movies.objects.all()


    args = {
        'movies': movies,
    }

    return render(request, 'core/index.html', args)



@login_required(login_url='core:login')
def movie(request, pk):
    movie_uuid = pk
    movie_details = Movies.objects.get(uu_id=movie_uuid)

    context = {
        'movie_details':movie_details
    }

    return render(request, 'core/movie.html', context)

@login_required(login_url='core:login')
def my_list(request):
  pass
   
@login_required(login_url='core:login')
def add_to_list(request):
    if request.method == 'POST':
        movie_url_id = request.POST.get('movie_id')
        # using regex (regular expression)
        uuid_pattern = r'[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}'
        match = re.search(uuid_pattern, movie_url_id)
        movie_id = match.group() if match else None

        movie = get_object_or_404(Movies, uu_id=movie_id)
        movie_list, created = MovieList.object.get_or_create(owner_user=request.user, movie=movie)

        if created:
            response_data = {'status': 'success', 'message': 'Added _/'}
        else:
            response_data = {'status':'info', 'message': 'Movie already in list'}

        return JsonResponse(response_data)
    else:
         return JsonResponse ({'status':'error', 'message': 'Invalid request'}, status=400) 
    

@login_required(login_url='core:login')
def search(request):

    if request.method == 'POST':
        search_term = request.POST['search_term']
        movies = Movies.objects.filter(title__icontains=search_term)

        context = {
            "movies": movies,
            "search_term": search_term,
        }
        return render(request, 'core/search.html', context)

    else:
        return redirect('/')


@login_required(login_url='core:login')  
def genre(request, pk):

    movie_genre = pk 

    movies = Movies.objects.filter(genre=movie_genre)

    data = {
        'movies': movies,
        'movie_genre': movie_genre,
    }

    return render(request, 'core/genre.html', data)


















# LOGIN AND REGISTER

def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(username=username, password=password)

        if user is not None:
            auth.login(request, user )
            return redirect('/')
        else:
            messages.error(request, 'Invalid Credentials')
            return redirect('core:login')

    else:
        return render(request, 'core/login.html')


def signup(request):
    if request.method == 'POST':
        name = request.POST['name']
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        password2 = request.POST['password2']

        if password == password2:
            if User.objects.filter(email=email).exists():
                messages.error(request, 'Email already exists')
                return redirect('core:signup')
            elif User.objects.filter(username=username).exists():
                messages.error(request, 'Username already taken')
                return redirect('core:signup')
            else:
                user = User.objects.create_user(username=username, email=email, password=password)
                user.save()

                # Log the user in
                user_login = auth.authenticate(username=username, password=password)
                auth.login(request, user_login)
                return redirect('/')

        else:
            messages.info(request, 'Password not matching')
            return redirect('core:signup')



    else:
        return render(request, 'core/register.html')


@login_required(login_url='core:login')
def logout(request):
    auth.logout(request)
    return redirect('core:login')

templates/core/detail-page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Netflix | detail page</title>
    <link rel="stylesheet" href="./css/style.css">
    <link rel="stylesheet" href="./bs/bootstrap.css">
    <link rel="icon" type="image/x-icon" href="./images/netflix.png">
</head>
<body class="details-body">
    <a class="navbar-brand detail-nav" href="index.html">
        <img src="./images/netflix-logo-0.png" alt="">

      </a>
    <section class="detail-main">
        
        <section class="detail-section">
            <div class="details">
                <div class="detail-image">
                <img src="./images/netflix.png" alt=""> <span class="fw-bold text-light">F I L M</span> 
                </div>
                <div class="detail-title">
                    <h2><b>KINGDOM</b></h2>
                </div>
                <div class="remaining-details">
                    <p class="mt-1">THE KINGDOM</p>
                    <P class="">2023 | <span class="rounded-1 btn btn-sm text-danger btn-outline-light">16+</span> | 2h 4m | Thrillers</P>
                    <p class="">After his son is framed for a kidnapping, a bereaved deacon takes justice into his own hands and fights a corrupt police gang to absolve him.</p>
                    <p>
                        <span class="text-danger">Starring:</span>
                        Richard Mofe-Damijo, Ade Laoye, Sam Dede
                    </p>
                </div>
            </div>
            
        </section>

        <section class="detail-section-two container my-4">
            <div class="detail-section-two-card">
                <div class="detail-section-two-logo">
                    <img src="./images/netflix.png" alt=""> <span class="fw-bold text-dark">Watch all you want.</span> 
                </div>
                <div class="detail-section-two-button">
                    <a href="./register.html" class="btn btn-sm btn-danger"> JOIN NOW</a>
                </div>
            </div>
        </section>

        <section class="detail-section-three container my-3 text-light">
            <h3>Videos | <span class="text-danger">Kingdom</span> </h3>

            <div>
                <a href="" class="video-section" data-bs-toggle="modal" data-bs-target="#exampleModal">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-play-circle" viewBox="0 0 16 16">
                    <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                    <path d="M6.271 5.055a.5.5 0 0 1 .52.038l3.5 2.5a.5.5 0 0 1 0 .814l-3.5 2.5A.5.5 0 0 1 6 10.5v-5a.5.5 0 0 1 .271-.445z"/>
                  </svg>
                </a>
            </div>
        </section>

        <section class="detail-section-four container">
            <h5 class="text-light py-3">More Details</h5>

            <div class="row">
                <div class="col-xl-3 col-md-3 col-sm-12">
                    <h6 class="text-light">Watch offline</h6>
                    <P class="mb-0">Download and watch everywhere you go.</P>
                </div>
                <div class="col-xl-3 col-md-3 col-sm-12">
                    <h6 class="text-light">Genres</h6>
                    <P class="mb-0">Nollywood, Crime Movies, Action & Adventure Movies, African Movies</P>
                </div>
                <div class="col-xl-3 col-md-3 col-sm-12">
                    <h6 class="text-light">Audio</h6>
                    <p class="mb-0">English - Audio Description, English [Original]</p>
                </div>
                <div class="col-xl-3 col-md-3 col-sm-12">
                    <h6 class=" text-light">Subtitle</h6>
                    <p class="mb-0">Arabic, English</p>
                </div>
            </div>

            <div class="row mt-3">
                <div class="col-xl-3 col-md-3 col-sm-12">
                    <h6 class="">Cast</h6>
                    <P class="mb-0">Richard Mofe-Damijo</P>
                    <p class="mb-0">Olumide Oworu</p>
                    <pmclass="mb-0">Taiwo Ajai-Lycett</pmclass=>
                </div>
                <div class="col-xl-3 col-md-3 col-sm-12">
                    <P class="mb-0">Ade Laoye</P>
                    <P class="mb-0">Kelechi Udegbe</P>
                </div>
                <div class="col-xl-3 col-md-3 col-sm-12">
                    <p class="mb-0">Sam Dede</p>
                    <p class="mb-0">Shaffy Bello</p>
                </div>
                <div class="col-xl-3 col-md-3 col-sm-12">
                    <p class="mb-0">Alex Usifo Omiagbo</p>
                    <p class="mb-0">Iretiola Doyle</p>
                </div>
            </div>
        </section>
    </section>



  <!-- Modal -->
  <div class="modal  fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered " >
      <div class="modal-content detail-section-three-modal"  role="document" >
        <div class="modal-header">
            <div class="first-movie-section">
                <h5><span class="fw-bold text-danger">|</span>  Trailer: <span class="text-danger">Kingdom</span> </h5>
              </div>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body  mx-auto bg-dark">
            <iframe class="img-fluid" width="469" height="315" src="https://www.youtube.com/embed/6ay4dt931bk?si=cMHZSrR1A48hpL75" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
        </div>
        <!-- <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary">Save changes</button>
        </div> -->
      </div>
    </div>
  </div>



  <script src="./bs/bootstrap.bundle.js"></script>
</body>
</html>

templates/core/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'core/css/style2.css' %}">
    <link rel="icon" type="image/x-icon" href="{% static 'core/images/netflix.png' %}">
    <link rel="stylesheet" href="{% static 'core/bs/bootstrap.css' %}">
    <title>Netflix | Login</title>
</head>
<body>
    
    <div class="section">
        <div class="image ">
    
          <div class="mx-4">
            <nav class="navbar navbar-expand-lg navbar-light" id="nav-bar">
                <div class="container-fluid">
                  <a class="navbar-brand" href="{% url "core:index" %}">
                      <img src="{% static 'core/images/netflix-logo-0.png' %}" alt="">
                  </a>
                  
                </div>
              </nav>
        
        </div>
    
        <section>
            <div class="section2 ">
                <div class="container">
                    <div class="title text-light">Sign In</div>
                    <p class="pt-3 pb-0 text-muted fw-light">Unlimited movies, TV shows, and more.</p>


                    <div class="text-center text-light my-3">
                        {% if messages %}
                        {% for message in messages %}
                            <div class="alert {% if message.tags == 'error' %}alert-danger {% elif message.tags == 'success' %}bg-success {% endif %} alert-dismissible fade show"  role="alert">
                                {{ message }}
                              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                            </div>
                        {% endfor %}
                        {% endif %}
                      </div>

                    <form method="post" action="">
                        {% csrf_token %}
                    
                        <div class="user-details">
                            <div class="input-box mt-5">
                                <span class="details text-light"> Username </span>
                                <input type="text" name="username"  placeholder="Username" required>
                            </div>
                            <div class="input-box mt-5">
                                <span class="details text-light"> Password </span>
                                <input type="password" name="password" placeholder="Password" required >
                            </div>
                        </div>
                        <div class="button mt-5 text-center">
                            <input type="submit" value="Login">
                        </div>
                        {% comment %} <div class="form-group check-box mt-2 d-flex gap-1">
                            <input type="checkbox" name="checkbox" class="form-check">
                            <span class="span1">Remember me</span>  <span class="text-light ms-auto span2"> Need help?</span>
                        </div> {% endcomment %}
                        <div class="small">
                            <p class="text-light pt-5">New to Netflix? <a href="{% url "core:signup" %}" class="text-light"> Sign up now.</a></p>
                            <p class="text-light">This page is protected by Google reCAPTCHA to ensure you're not a bot. <a href="#">Learn more.</a></p>
                        </div>
                    </form>
                
                    
                    
                </div>
                
            </div>
        </section>


    </div>


</body>
<script src="{% static 'core/bs/bootstrap.bundle.js' %}"></script>
</html>

templates/core/movie.html
{% load static %}
{% load humanize %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Netflix | detail page</title>
    <link rel="stylesheet" href="{% static 'core/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'core/bs/bootstrap.css' %}">
    <link rel="icon" type="image/x-icon" href="{% static 'core/images/netflix.png' %}">
</head>
<body class="details-body">
    <nav class="navbar navbar-expand-lg bg-body-tertiary fixed-top">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'core:index' %}">
                <img src="{% static 'core/images/netflix-logo-0.png' %}" alt="">
            </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              
            </ul>
          </div>
        </div>
      </nav>
        
    <section class="detail-main">
        
        <section class="detail-section" style="background-image: linear-gradient(to left, transparent -100%, black 100%), url('{{movie_details.image_cover.url}}');
        background-size:cover;
        background-position: center;
        background-repeat: no-repeat;
        ">
            <div class="details">
                <div class="detail-image">
                <img src="{% static './images/netflix.png' %}" alt=""> <span class="fw-bold text-light">F I L M</span> 
                </div>
                <div class="detail-title">
                    <h2><b>{{movie_details.title}}</b></h2>
                </div>
                <div class="remaining-details">
                    <p class="mt-1">{{movie_details.title}}</p>
                    <P class="">{{movie_details.release_date|naturalday}} | <span class="rounded-1 btn btn-sm text-danger btn-outline-light">{{movie_details.parental_rating}}+</span> | {{movie_details.length}} hr(s) | {{movie_details.genre}}</P>
                    <p class="">{{movie_details.description}}</p>
                    <p>
                        <span class="text-danger">Starring:</span>
                    </p>
                </div>
            </div>
            
        </section>

        <section class="detail-section-two container my-4">
            <div class="detail-section-two-card">
                <div class="detail-section-two-logo">
                    <img src="{% static 'core/images/netflix.png' %}" alt=""> <span class="fw-bold text-dark">Watch all you want.</span> 
                </div>
                {% if user.is_authenticated %}

                {% else %}
                <div class="detail-section-two-button">
                    <a href="./register.html" class="btn btn-sm btn-danger"> JOIN NOW</a>
                </div>
                {% endif %}
            </div>
        </section>

        <section class="detail-section-three container my-3 text-light">
            <h3>Videos | <span class="text-danger">{{movie_details.title}}</span> </h3>

            <div>
                <video class="video-section" controls>
                    <source src="{{movie_details.video.url}}" type="video/mp4">
                    Your browser does not support the video tag.
                </video>
            </div>
        </section>

        <section class="detail-section-four container">
            <h5 class="text-light py-3">More Details</h5>

            <div class="row">
                <div class="col-xl-3 col-md-3 col-sm-12">
                    <h6 class="text-light">Watch offline</h6>
                    <P class="mb-0">Download and watch everywhere you go.</P>
                </div>
                <div class="col-xl-3 col-md-3 col-sm-12">
                    <h6 class="text-light">Genres</h6>
                    <P class="mb-0">Nollywood, Crime Movies, Action & Adventure Movies, African Movies</P>
                </div>
                <div class="col-xl-3 col-md-3 col-sm-12">
                    <h6 class="text-light">Audio</h6>
                    <p class="mb-0">English - Audio Description, English [Original]</p>
                </div>
                <div class="col-xl-3 col-md-3 col-sm-12">
                    <h6 class=" text-light">Subtitle</h6>
                    <p class="mb-0">Arabic, English</p>
                </div>
            </div>

            <div class="row mt-3">
                <div class="col-xl-3 col-md-3 col-sm-12">
                    <h6 class="">Cast</h6>
                    <P class="mb-0">Richard Mofe-Damijo</P>
                    <p class="mb-0">Olumide Oworu</p>
                    <pmclass="mb-0">Taiwo Ajai-Lycett</pmclass=>
                </div>
                <div class="col-xl-3 col-md-3 col-sm-12">
                    <P class="mb-0">Ade Laoye</P>
                    <P class="mb-0">Kelechi Udegbe</P>
                </div>
                <div class="col-xl-3 col-md-3 col-sm-12">
                    <p class="mb-0">Sam Dede</p>
                    <p class="mb-0">Shaffy Bello</p>
                </div>
                <div class="col-xl-3 col-md-3 col-sm-12">
                    <p class="mb-0">Alex Usifo Omiagbo</p>
                    <p class="mb-0">Iretiola Doyle</p>
                </div>
            </div>
        </section>
    </section>



  <!-- Modal -->
  <div class="modal  fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered " >
      <div class="modal-content detail-section-three-modal"  role="document" >
        <div class="modal-header">
            <div class="first-movie-section">
                <h5><span class="fw-bold text-danger">|</span>  Trailer: <span class="text-danger">Kingdom</span> </h5>
              </div>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body  mx-auto bg-dark">
            <iframe class="img-fluid" width="469" height="315" src="https://www.youtube.com/embed/6ay4dt931bk?si=cMHZSrR1A48hpL75" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
        </div>
        <!-- <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary">Save changes</button>
        </div> -->
      </div>
    </div>
  </div>



  <script src="{% static 'core/bs/bootstrap.bundle.js' %}"></script>
</body>
</html>

templates/core/register.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'core/css/style2.css' %}">
    <link rel="icon" type="image/x-icon" href="{% static 'core/images/netflix.png' %}">
    <link rel="stylesheet" href="{% static 'core/bs/bootstrap.css' %}">
    <title>Netflix | SignUp</title>
</head>
<body>
    
    <div class="section">
        <div class="image ">
    
          <div class="mx-5">
            <nav class="navbar navbar-expand-lg navbar-light" id="nav-bar">
                <div class="container-fluid">
                  <a class="navbar-brand" href="{% url 'core:index' %}">
                      <img src="{% static 'core/images/netflix-logo-0.png' %}" alt="">
                  </a>
                  
                </div>
              </nav>
        
        </div>
    
        <section>
            <div class="section2 ">
                <div class="container">
                    <div class="title text-light">Sign Up</div>

                    <div class="text-center text-light col-md-4 col-sm-12 my-3">
                        {% if messages %}
                        {% for message in messages %}
                            <div class="alert {% if message.tags == 'error' %}alert-danger{% elif message.tags == 'success' %}alert-success{% endif %} alert-dismissible fade show"  role="alert">
                                {{ message }}
                              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                            </div>
                        {% endfor %}
                        {% endif %}
                      </div>
                    <form method="POST" action="" autocomplete="off" spellcheck="true">
                        {% csrf_token %}
                    
                        <div class="user-details">
                            <div class="row">
                                <div class="col-xl-6">
                                    <div class="input-box mt-3">
                                        <span class="details text-light"> Name </span>
                                        <input type="text" name="name" placeholder="your name..." required >
                                    </div>
                                </div>
                                <div class="col-xl-6">
                                    <div class="input-box mt-3">
                                        <span class="details text-light"> Username </span>
                                        <input type="text" name="username" placeholder="your username...">
                                    </div>
                                </div>
                            </div>
                            <div class="input-box mt-2">
                                <span class="details text-light"> Email </span>
                                <input type="text" name="email"  placeholder="your email..." required>
                            </div>
                            <div class="row">
                                <div class="col-xl-6">
                                    <div class="input-box mt-2">
                                        <span class="details text-light"> Password </span>
                                        <input type="password" name="password" placeholder="Password" required >
                                    </div>
                                </div>
                                <div class="col-xl-6">
                                    <div class="input-box mt-2">
                                        <span class="details text-light"> Confirm Password </span>
                                        <input type="password" name="password2" placeholder="Password" required >
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="button mt-3 text-center">
                            <input type="submit" value="Signup">
                        </div>
                        <div class="form-group check-box mt-2 d-flex gap-1">
                            <input type="checkbox" name="checkbox" class="form-check">
                            <span class="span1">Remember me</span>  <span class="text-light ms-auto span2"> Need help?</span>
                        </div>
                        <div class="small">
                            <p class="text-light pt-4">Already have an account? <a href="{% url "core:login" %}" class="text-light"> Sign in.</a></p>
                            <p class="text-light">This page is protected by Google reCAPTCHA to ensure you're not a bot. <a href="#">Learn more.</a></p>
                        </div>
                    </form>
                
                    
                    
                </div>
                
            </div>
        </section>


    </div>


</body>
<script src="{% static 'core/bs/bootstrap.bundle.js' %}"></script>
</html>